#!/usr/local/bin/python2.7

import smtplib
import db_functions
from email.MIMEMultipart import MIMEMultipart
from email.MIMEText import MIMEText

def sendPollCreatedEmail(email_addr, poll_link):
    msg_body = "This is an automated message generated by WhenAndWhere.\n"
    msg_body += "You can access your poll here: \ncs.wellesley.edu:9876/poll_response/" + poll_link 
    msg_body += "\nand the responses to your poll at cs.wellesley.edu:9876/view_responses/" + poll_link

    msg = MIMEMultipart()
    msg['From'] = 'sfrankia@tempest.wellesley.edu'
    msg['To'] = email_addr
    msg['Subject'] = 'Your WhenAndWhere Poll'
    
    msg.attach(MIMEText(msg_body,'plain'))
    server = smtplib.SMTP('localhost')
    server.sendmail('sfrankia@tempest.wellesley.edu',email_addr,msg.as_string())
    server.quit()

def sendExpirationReminder(email_addr):
    msg_body = "This is an automated message generated by WhenAndWhere.\n"
    msg_body += "A poll you created is expiring today. Please remind your voters to vote if they have not done so already."

    msg = MIMEMultipart()
    msg['From'] = 'sfrankia@tempest.wellesley.edu'
    msg['To'] = email_addr
    msg['Subject'] = 'Your WhenAndWhere Poll Expires Today'
    
    msg.attach(MIMEText(msg_body,'plain'))
    server = smtplib.SMTP('localhost')
    server.sendmail('sfrankia@tempest.wellesley.edu',email_addr,msg.as_string())
    server.quit()

def sendResults(email_addr,results):
    msg_body = "This is an automated message generated by WhenAndWhere.\n"
    msg_body += "A poll you created expired today. Here are the final voting results.\n"
    msg_body += "\nOPTION\t\t\t\t\tVOTES\n\n"
    
    for result in results:
        msg_body += result['meeting_date'].strftime('%m/%d/%Y') + ", " + str(result['given_time']) + " at " + result['location'] + '\t\t\t' + str(result['response']) + '\n'

    msg = MIMEMultipart()
    msg['From'] = 'sfrankia@tempest.wellesley.edu'
    msg['To'] = email_addr
    msg['Subject'] = 'Your WhenAndWhere Poll Results'
    
    msg.attach(MIMEText(msg_body,'plain'))
    server = smtplib.SMTP('localhost')
    server.sendmail('sfrankia@tempest.wellesley.edu',email_addr,msg.as_string())
    server.quit()



