#!/usr/bin/python

import smtplib

def sendPollCreatedEmail(email_addr, poll_link):
    message = "From: WhenAndWhere <sfrankia@cs.wellesley.edu> To: " + 
    email_addr + " <" + email_addr + ">" + 
    """MIME-Version: 1.0
    Content-type: text/html
    Subject: Your WhenAndWhere Poll
    
    <p>This is an automated message generated by WhenAndWhere.</p>
    <p>You can access your poll <a href=' """ + poll_link + " '> here </a> " 

    try:
        smtpObj = smtplib.STMP('localhost')
        smtpObj.sendmail('sfrankia@cs.wellesley.edu',email_addr,message)
    except SMTPException:
        print "ERROR sending email"
